In [40]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [41]:
df_train = pd.read_csv("SalaryData_Train.csv")
df_train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [42]:
df_train.shape

(30161, 14)

In [43]:
df_train['workclass'].value_counts()

 Private             22285
 Self-emp-not-inc     2499
 Local-gov            2067
 State-gov            1279
 Self-emp-inc         1074
 Federal-gov           943
 Without-pay            14
Name: workclass, dtype: int64

In [44]:
df_train['education'].value_counts()

 HS-grad         9840
 Some-college    6677
 Bachelors       5044
 Masters         1627
 Assoc-voc       1307
 11th            1048
 Assoc-acdm      1008
 10th             820
 7th-8th          557
 Prof-school      542
 9th              455
 12th             377
 Doctorate        375
 5th-6th          288
 1st-4th          151
 Preschool         45
Name: education, dtype: int64

In [45]:
df_train['educationno'].value_counts()

9     9840
10    6677
13    5044
14    1627
11    1307
7     1048
12    1008
6      820
4      557
15     542
5      455
8      377
16     375
3      288
2      151
1       45
Name: educationno, dtype: int64

In [46]:
df_train['maritalstatus'].value_counts()

 Married-civ-spouse       14065
 Never-married             9725
 Divorced                  4214
 Separated                  939
 Widowed                    827
 Married-spouse-absent      370
 Married-AF-spouse           21
Name: maritalstatus, dtype: int64

In [47]:
df_train['occupation'].value_counts()

 Prof-specialty       4038
 Craft-repair         4030
 Exec-managerial      3992
 Adm-clerical         3721
 Sales                3584
 Other-service        3212
 Machine-op-inspct    1965
 Transport-moving     1572
 Handlers-cleaners    1350
 Farming-fishing       989
 Tech-support          912
 Protective-serv       644
 Priv-house-serv       143
 Armed-Forces            9
Name: occupation, dtype: int64

In [48]:
df_train['relationship'].value_counts()

 Husband           12463
 Not-in-family      7726
 Own-child          4466
 Unmarried          3212
 Wife               1406
 Other-relative      888
Name: relationship, dtype: int64

In [49]:
df_train['race'].value_counts()

 White                 25932
 Black                  2817
 Asian-Pac-Islander      895
 Amer-Indian-Eskimo      286
 Other                   231
Name: race, dtype: int64

In [50]:
df_train['sex'].value_counts()

 Male      20380
 Female     9781
Name: sex, dtype: int64

In [51]:
df_train['capitalgain'].value_counts()

0        27623
15024      337
7688       270
7298       240
99999      148
         ...  
1639         1
6097         1
2538         1
1455         1
1086         1
Name: capitalgain, Length: 118, dtype: int64

In [52]:
df_train['hoursperweek'].value_counts()

40    14250
50     2718
45     1753
60     1405
35     1184
      ...  
82        1
94        1
92        1
87        1
74        1
Name: hoursperweek, Length: 94, dtype: int64

In [53]:
df_train['native'].value_counts()

 United-States                 27504
 Mexico                          610
 Philippines                     188
 Germany                         128
 Puerto-Rico                     109
 Canada                          107
 India                           100
 El-Salvador                     100
 Cuba                             92
 England                          86
 Jamaica                          80
 South                            71
 China                            68
 Italy                            68
 Dominican-Republic               67
 Vietnam                          64
 Guatemala                        63
 Japan                            59
 Poland                           56
 Columbia                         56
 Iran                             42
 Taiwan                           42
 Haiti                            42
 Portugal                         34
 Nicaragua                        33
 Peru                             30
 Greece                           29
 

In [54]:
df_train['Salary'].value_counts()

 <=50K    22653
 >50K      7508
Name: Salary, dtype: int64

In [55]:
# Data transformation for train data set
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

for i in range(1,14):
    df_train.iloc[:,i] = LE.fit_transform(df_train.iloc[:,i])

df_train.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           12              4           0   
1   50          4          9           12              2           3   
2   38          2         11            8              0           5   
3   53          2          1            6              2           5   
4   28          2          9           12              2           9   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1           24            0            39      37   
1             0     4    1            0            0            12      37   
2             1     4    1            0            0            39      37   
3             0     2    1            0            0            39      37   
4             5     2    0            0            0            39       4   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0

In [56]:
# split the variables as two parts
X_train = df_train.iloc[:,0:13]
Y_train = df_train.iloc[:,13]

In [57]:
X_train

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           12              4           0   
1       50          4          9           12              2           3   
2       38          2         11            8              0           5   
3       53          2          1            6              2           5   
4       28          2          9           12              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           11              2          12   
30157   40          2         11            8              2           6   
30158   58          2         11            8              6           0   
30159   22          2         11            8              4           0   
30160   52          3         11            8              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 1     4    1           24            0            39      37  
1                 0     4    1            0            0            12      37  
2                 1     4    1            0            0            39      37  
3                 0     2    1            0            0            39      37  
4                 5     2    0            0            0            39       4  
...             ...   ...  ...          ...          ...           ...     ...  
30156             5     4    0            0            0            37      37  
30157             0     4    1            0            0            39      37  
30158             4     4    0            0            0            39      37  
30159             3     4    1            0            0            19      37  
30160             5     4    0          107            0            39      37  

[30161 rows x 13 columns]

In [58]:
Y_train

0        0
1        0
2        0
3        0
4        0
        ..
30156    0
30157    1
30158    0
30159    0
30160    1
Name: Salary, Length: 30161, dtype: int32

In [59]:
# Model fitting  
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB()
MNB.fit(X_train,Y_train)

MultinomialNB()

In [60]:
Y_pred_train = MNB.predict(X_train)

In [61]:
Y_pred_train

array([1, 0, 0, ..., 0, 0, 1])

In [62]:
df_test = pd.read_csv("SalaryData_Test.csv")
df_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [63]:
df_test.shape

(15060, 14)

In [64]:
# Data transformation for test data set
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

for i in range(1,14):
    df_test.iloc[:,i] = LE.fit_transform(df_test.iloc[:,i])

df_test.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            6              4           6   
1   38          2         11            8              2           4   
2   28          1          7           11              2          10   
3   44          2         15            9              2           6   
4   34          2          0            5              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            39      37   
1             0     4    1            0            0            49      37   
2             0     4    1            0            0            39      37   
3             0     2    1           87            0            39      37   
4             1     4    1            0            0            29      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0

In [65]:
# split the variables as two parts
X_test = df_test.iloc[:,0:13]
Y_test = df_test.iloc[:,13]

In [66]:
X_test

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            6              4           6   
1       38          2         11            8              2           4   
2       28          1          7           11              2          10   
3       44          2         15            9              2           6   
4       34          2          0            5              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           12              4           9   
15056   39          2          9           12              0           9   
15057   38          2          9           12              2           9   
15058   44          2          9           12              0           0   
15059   35          3          9           12              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 3     2    1            0            0            39      37  
1                 0     4    1            0            0            49      37  
2                 0     4    1            0            0            39      37  
3                 0     2    1           87            0            39      37  
4                 1     4    1            0            0            29      37  
...             ...   ...  ...          ...          ...           ...     ...  
15055             3     4    1            0            0            39      37  
15056             1     4    0            0            0            35      37  
15057             0     4    1            0            0            49      37  
15058             3     1    1           73            0            39      37  
15059             0     4    1            0            0            59      37  

[15060 rows x 13 columns]

In [67]:
Y_test

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: Salary, Length: 15060, dtype: int32

In [68]:
Y_pred_test = MNB.predict(X_test)

In [69]:
Y_pred_test

array([0, 0, 0, ..., 0, 1, 0])

In [70]:
# metrics calculation
from sklearn.metrics import confusion_matrix, accuracy_score

Training_score = accuracy_score(Y_train,Y_pred_train)
Test_score = accuracy_score(Y_test,Y_pred_test)

In [71]:
print("Training score",Training_score.round(5))
print("Test score",Test_score.round(5))

Training score 0.77932
Test score 0.78028


In [72]:
cm_test = confusion_matrix(Y_test,Y_pred_test)
cm_test

array([[10632,   728],
       [ 2581,  1119]], dtype=int64)

In [73]:
cm_train = confusion_matrix(Y_train,Y_pred_train)
cm_train

array([[21178,  1475],
       [ 5181,  2327]], dtype=int64)

In [74]:
print(classification_report(Y_train, Y_pred_train))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86     22653
           1       0.61      0.31      0.41      7508

    accuracy                           0.78     30161
   macro avg       0.71      0.62      0.64     30161
weighted avg       0.76      0.78      0.75     30161



In [75]:
print(classification_report(Y_test, Y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.94      0.87     11360
           1       0.61      0.30      0.40      3700

    accuracy                           0.78     15060
   macro avg       0.71      0.62      0.63     15060
weighted avg       0.76      0.78      0.75     15060



In [76]:
# log loss calculation
from sklearn.metrics import log_loss
logloss_train=log_loss(Y_train,Y_pred_train)
logloss_test=log_loss(Y_test,Y_pred_test)

In [77]:
print("logloss_train : ",logloss_train.round(3))
print("logloss_test : ",logloss_test.round(3))

logloss_train :  7.622
logloss_test :  7.589
